src/components/checkout/CartItem.vue

Added trim and trailing ellipsis for items longer than 15 characters. Prevents cart quantity vertical alignment.

Bugfix for #35

---

src/views/Home.vue

Addresses Issue #33, replaces PR #46

feat: sticky cta order now button on mobile works

---

src/components/Navbar.vue

chore: unsticky nav bar

---

src/components/cart/CartItem.vue

style: changed cart item quantity to white

---

src/App.vue

Removed Navbar. See issue #55.

chore: remove top nav from site

---

src/components/Footer.vue

Implemented additional features requested on  #12

feat: add google map links on footer address

---

src/components/cart/EmptyCart.vue
src/views/Home.vue

chore: hide cart header and empty cart component on mobile

---

src/components/cart/Cart.vue
src/components/cart/CartItem.vue

This addresses Issue #36. 
I'm not sure if it matters too much, but I'd rather not use the custom CSS, so please let me know if there's a way to do it with just Tailwind utilities. I was referencing [this](https://tailwindcss.com/docs/transition-property/) and tried a few things.

feat: animate cart items on enter and leave

---

src/views/Home.vue

chore: increase border radius on order now cta button

---

src/components/forms/CustomerAddress.vue
src/components/forms/CustomerInfo.vue

fix: show form errors only after users attempts input/submit

---

src/components/Button.vue
src/components/forms/CheckoutNavBar.vue
src/views/Home.vue

This addresses Issue #109 
We update the Button component's styles. We update Button component usage instances accordingly.

chore: update button component style and usage instances

---

src/components/forms/CheckoutForm.vue
src/components/forms/CheckoutStepper.vue

This partially addresses Issue #97 (the other parts are addressed in PR #98).
In this PR, we
1. animate the progress bar on the Checkout Stepper component whenever the customer switches page on the Checkout Form
2. fade in page when the customer switches page on the Checkout Form

feat: checkout progress nav refresh (pt 2)

---

src/components/cart/Cart.vue
src/views/Home.vue

This addresses Issues #119 and also a small issue that was being addressed in #54 but never approved

Fix: displayed prices

---

src/App.vue
src/components/CreditFooter.vue
tailwind.config.js

This is in reference to "Add Footer Credit #99".

Feat: Added Credit Footer

---

CONTRIBUTING.md
README.md

Contributor guide as also been updated ot include instructions on how to use fetch
https://github.com/whynotearth/whynot.earth/wiki/New-Contributor-Guide

Added detailed new contributor guide link

---

CONTRIBUTING.md
README.md
package-lock.json
package.json
public/index.html
src/App.vue
src/assets/tailwind.css
src/components/CreditFooter.vue
src/components/Navbar.vue
src/components/cards/CardHolder.vue
src/components/cards/ProductCard.vue
src/components/cart/Cart.vue
src/components/cart/CartItem.vue
src/components/categories/CategoryHolder.vue
src/components/forms/CheckoutForm.vue
src/components/forms/DeliveryTime.vue
src/components/forms/ReviewOrder.vue
src/layouts/Default.vue
src/layouts/ShopLayout.vue
src/main.js
src/router/index.js
src/store/modules/cart.js
src/store/modules/home.js
src/store/modules/shop.js
src/views/Home.vue
src/views/Shop.vue
tailwind.config.js

Reverts to commit ba994ca which was the merge commit for PR #149

revert to merge commit ba994ca

---

src/components/forms/CheckoutForm.vue
src/components/forms/CustomerAddress.vue
src/components/forms/CustomerInfo.vue
src/components/forms/DeliveryTime.vue
src/components/forms/PaymentMethod.vue
src/components/forms/ReviewOrder.vue
src/components/forms/ThankYou.vue
src/router/index.js
src/views/Shop.vue

142 Add routes for ordering form on page changes

---

src/views/Home.vue

chore: include credit footer component on home view

---

src/components/LayoutFixedScrollable.vue

https://github.com/whynotearth/foodouken.com/issues/196#top-nav

layoutFixedScrollbar component added

---

src/components/inputs/BaseToggleSwitch.vue

there is no related issue
[ ] Bug Fix
[ ] Refactor
Toggle Switch component created, same component used as in the Volkswagen project but toggle handling done at base component level and two way binding part done.
You can test this component at #215 merge request at https://deploy-preview-215--foodouken.netlify.app/auth/sign-up/business-hours after clicking a hour to open modal
If applicable, include any relevant …

toggle switch component created

---

src/components/TimePicker.vue
src/helpers.js

#183 
[ ] Bug Fix
[ ] Refactor
This PR is related to time selection component. It uses 3 smooth picker component to provide style and customization easily. And putting colon between hour and minutes. It takes 09:00:00 as v-model and converts to 09:00 AM inside component using helpers then emits for example 10:00:00 to model
1.Go to link https://deploy-preview-215--foodouken.netlify.app/auth/sign-up/business-hours
3. …

timepicker component created

---

src/components/auth/SignUpForm.vue
src/components/tenant/LinkAccount.vue
src/components/tenant/Notifications.vue
src/components/tenant/PaymentMethods.vue

#232 
[ ] Bug Fix
[x] Refactor
Added validations to sign up flow
1- Go https://deploy-preview-233--foodouken.netlify.app/welcome
2- Click Start setting business button
3- Fill business info partly and wrongly then click next
4- without loging in click next
5- then login it will redirect you next step automatically
6- deselect selected notification types and click next, after seeing error select one then click next
7- Edit business hours then click next
8- deselect …

sign up validations done

---

src/components/tenant/LinkAccount.vue
src/components/tenant/Notifications.vue
src/router/authRoutes.js
src/store/modules/auth.js
src/store/modules/tenant.js
src/views/AuthSignUp.vue

#231 #234 #235 
[x] Bug Fix
[x] Refactor
Related issues solved at the Issue Being Addressed  field
I removed isSignUpStarted variable from auth store because I'm controlling it via route changes
1- Same as testing whole sign up flow
Provide any additional notes that you think would help effective review of …

sign up issues done

---

src/components/inputs/QuantityInput.vue

This issue related to quantity input at issue #108 to make input general and use whole around the app.
[ ] Bug Fix
[ ] Refactor
We use counter input a lot at foodouken project so I thought creating a component would be more efficient and will increase development time. 
Test details will be provided after creating product page PR.
Provide any additional notes that you think would help effective review of …

quantity input created

---

src/components/cards/ProductCard.vue
src/components/categories/Category.vue
src/components/categories/CategoryHolder.vue
src/store/modules/category.js

No related issue
[x] Bug Fix
[x] Refactor
Category and product images were array of images before coming from backend now its key and type changed. To solve this I put correct key where bug occured.
New endpoints integrated to customer view at category.js
**For Feature Updates:** …

Customer view new endpoints

---

src/components/auth/SignUpForm.vue
src/components/inputs/TimePicker.vue

https://github.com/whynotearth/foodouken.com/issues/250
[x] Bug Fix
[ ] Refactor
At sign up flow users could enter url and start with any step they want. I solved this via redirecting to businessInfo.
TimePicker component hadn't have wheel event support. I added wheel event support …

Tenant creation fixes

---

src/store/modules/auth.js

[x] Bug Fix
[ ] Refactor
Google auth had problem after successful login with no hash in return Url, so i added it
**For Other:** State what 'type' of PR yours is and elaborate on …

google auth redirection problem fixed

---

netlify.toml

feat: add production api url

---

src/components/auth/SignUpForm.vue
src/components/tenant/LinkAccount.vue
src/router/authRoutes.js
src/store/modules/auth.js
src/views/AuthLogIn.vue

https://github.com/whynotearth/foodouken.com/issues/257
[x] Bug Fix
[ ] Refactor
Sign up had problem with looping back to normal state. Because it was checking hash at the returnUrll but at some case it doesn't have it so it was crushing now I sent query and it's working fine.
**For …

Sign up loop

---

src/components/BaseAPIErrorDisplay.vue
src/views/MenuCategoryAddEdit.vue
src/views/MenuItemAddEdit.vue
src/views/Shop.vue

Fixes/ API error display and min-height

---

src/components/Dropdown.vue
src/views/MenuItemAddEdit.vue

Adding v-click-outside is the source of this bug in iOS. Removing it from Dropdown.vue, seems fixes the problem.

fix input tap ios

---

src/store/index.js

No related issue at the dashboard. 
[ ] Bug Fix
[x] Refactor
I moved tenant store from localStorage to sessionStorage because @atharva3010 's changes on notification types and payment methods didn't get affected because of the storing tenant store at localStorage.
**For Feature …

refactor: tenant store moved from local to session storage

---

src/components/auth/AuthButtons.vue

[ ] Bug Fix
[ ] Refactor
[x] Other (state below)
Facebook option commented from authButtons.
Provide steps on …

facebook auth option removed

---

src/components/inputs/TimePicker.vue
src/components/tenant/BusinessHoursModal.vue
src/helpers.js
src/store/modules/tenant.js

https://github.com/whynotearth/foodouken.com/issues/273
[x] Bug Fix
[x] Refactor
helper.js time extraction functions updated according to 12 am selection. 
if time is 23:59:59 comes from backend there is no place to show it at the timepicker component that's why I set correct values for this case at timepicker.vue
BusinessHoursModal checks difference between opening and closing …

Time selection business hours

---

src/components/menu/VariantManager.vue
src/views/MenuItemAddEdit.vue

#271 
[ ] Bug Fix
[x] Refactor
At Adding and editing menu items page there was no validation for variation and extras. I put vuelidate validations to this fields.
**For Other:** …

Variant manager validations

---

src/components/BaseStepperBottomBar.vue
src/components/forms/CheckoutStepper.vue
src/components/forms/ReviewOrder.vue
src/registerServiceWorker.js
src/store/modules/tenant.js
src/views/MenuItemList.vue

Staging to master

---

.env
src/components/forms/CustomerAddress.vue
src/components/inputs/FindLocation.vue

#264 
[ ] Bug Fix
[x] Refactor
User location finder component created to imitate tinder-like behavior . And refactored customer address respectively. 
**For Other:** State what …

User location finder

---

src/store/modules/form.js

stagin to master

---

src/components/inputs/FindLocation.vue
src/components/tenant/BusinessHoursModal.vue
src/views/MenuItemAddEdit.vue

#299 
[ ] Bug Fix
[ ] Refactor
[x] Other (state below)
Unused sections commented
and lint warnings fixed
Provide …

299 hide unused sections

---

README.md

Update README.md to include logo

---

src/components/cards/ProductCard.vue

#308 
[x] Bug Fix
[ ] Refactor
2. Go to '...'
4. See the …

break-words class added in ProductCard Component. refs #308

---

src/components/inputs/BaseToggleSwitch.vue

This is a hotfix
[x] Bug Fix
[ ] Refactor
**For Bug Fixes:** Fix id of BaseToggleSwitch component which was consistent.
Open a page with two toggles and test if both of them are toggling correctly
Related to a question in discord about this PR #307

hotfix toggle switch id issue

---

src/views/Home.vue

#336 
[x] Bug Fix
[ ] Refactor …

added nav gaurds to prevent redirect to inactive tenants. refs #336

---

src/store/modules/tenant.js
src/views/SettingsAccount.vue

No issue
[x] Bug Fix
[ ] Refactor
Go to My account (list of tenants) and change status of your tenants

Change active status for multiple tenants

---

src/components/cards/ProductCard.vue
src/components/cart/CartItem.vue
src/components/inputs/MaterialInput.vue
src/store/modules/cart.js
src/views/Promotion.vue

#332 
[ ] Bug Fix
[ ] Refactor
2. Go to '...'
4. See the …

Promotion changes added to shop and cart layouts. refs #332

---

src/views/MenuItemAddEdit.vue
src/views/MenuItemList.vue
src/views/Promotion.vue

#359 
[x] Bug Fix
[ ] Refactor …

fixed pricing issue while editing item. refs #359

---

src/views/SettingsAccount.vue

added business setup button with navigation. refs #286

---

src/router/index.js

adding empty states into master

Staging to master add empty state

---

src/views/MenuItemAddEdit.vue
src/views/SettingsAccount.vue

#370 
[x] Bug Fix
[ ] Refactor
2. Go to '...'
4. See the …

hotfix added default value for discout percent. refs #370

---

src/components/SnackBar.vue
src/views/Home.vue

review comments fixed. refs #201

---

src/App.vue
src/views/Home.vue

#201 
[ ] Bug Fix
[x] Refactor …

hotfix: added snackbar in app.vue refs #201

---

src/App.vue
src/views/Home.vue

[x] Bug Fix
[ ] Refactor
**For Bug Fixes:** 
- What was the root cause? 
There were two snackbars one in App.vue and one in Home.vue 
- How do your changes fix the bug effectively?
Removed the Snackbar from the Home.vue
- Open the app in your browser and you should see the snack bar
- Click on agree to make it disappear.

hotfix: removed duplicated snackbar

---

src/layouts/Default.vue
src/layouts/ShopLayout.vue

#392
[ ] Bug Fix
[ ] Refactor
[x ] Update to Existing Feature
I updated the Announcement Banner by commenting it out in Default.vue and ShopLayout.vue within the Layout folder.
2. Go to 'foodouken.com' and check banner is gone.
4. See the updated element x
Provide any additional notes that you think …

392 disable announcement banner

---

src/layouts/Default.vue
src/layouts/ShopLayout.vue
src/router/customerViewRoutes.js
src/views/PrivacyPolicy.vue

#387 
[ ] Bug Fix
[ ] Refactor
[ x] Other (state below)
Simply commented out the login spans in Default.vue and ShopLayout.vue.
It may not be what was required, but here's hoping!
2. Go to 'www.foodouken.com'
4. See the updated element x
Provide any additional notes that you think would help effective review of your code.

Hide login button

---

src/router/customerViewRoutes.js
src/views/PrivacyPolicy.vue

#393 
[ ] Bug Fix
[ ] Refactor
[x ] Other (state below)
Updated the privacy policy styling.
Removed (commented out) some of the tenant features at the bottom, but was unable to remove all of them without errors. Please advise.
2. Go to 'www.foodouken.com/privacy-policy'
4. See the updated element x
Provide any additional notes that you think would help effective review of your code.

Privacy policy update

---

src/components/CreditFooter.vue

footer update

---

src/components/CreditFooter.vue

footer-updates

---

package.json
src/main.js
yarn.lock

#354
[ ] Bug Fix
[ ] Refactor
Added Roll Bar Error logger to get a holistic view of errors happening when people are ordering food.
1. Go to the site and make an error
2. Notice in the 'Network' tab there was an API call to rollbar
Please check Rollbar reporting to make sure the connection is working

added rollbar error logger

---

src/components/forms/ReviewOrder.vue

#248 
[ ] Bug Fix
[ ] Refactor
Type of items / how often they are ordered / how many items are ordered in one session / where users are coming from when ordering / other data is available to use now. Once they complete a checkout.
1. Go to the site. Make sure network tab is open
2. Make an order
3. Filter for **google-analytics**
4. Notice a Google Analytics beacon fired with the order data sent along.
Font-end
Google Analytics

see what products are being purchased and user behavior in GA

---

vue.config.js

[x] Refactor
Fix exposing source code in devtools

Hide sourcemap in production
