src/components/inputs/MaterialInput.vue, src/components/inputs/TextArea.vue, tailwind.config.js
This addresses Issue #49 
- placeholders on inputs and textarea elements disappear on focus/active
- increased border width on input and textarea elements on focus/active
=> chore: placeholders on inputs and textareas disappear on focus

src/components/categories/Category.vue
Addresses #30 - original treatment of this issue made the categories too close together.
=> chore: increase margin between categories slightly horizontally

src/components/cards/ProductCard.vue
This addresses issue #87 
Now when hovering over a product card, the card and the button inside of it will have their opacities reduced at the same time
An issue might be that the transition durations for the parent div's opacity and the button's background differ by a slight amount, but there is no `duration-400` class utility in Tailwind that I could put on the parent div to exactly match the existing `transition: background 0.4s;` on the button. If this is not fine, then we can change the CSS by 0.1s
=> feat:product card opacity decrease on hover

src/components/categories/CategoryHolder.vue
We left-align categories in the category holder to avoid the "for you" icon to become obscured if there are too many categories, like so:
After fix:
=> chore: justify content default on category holder

src/components/Button.vue
We remove the uppercase utility from the button component as discussed with @paulchrisluke
=> chore: remove uppercase utility from button component

src/App.vue, src/store/modules/home.js, src/views/Home.vue
When we switch between categories, we show the loading "spinner" component. We also add fade transitions between spinner and category components to make for a smoother experience.
=> feat: add transitions and spinners while category loads

src/components/Button.vue, src/components/forms/CheckoutForm.vue, src/components/forms/CheckoutNavBar.vue, src/components/forms/CheckoutStepper.vue, src/components/forms/CustomerAddress.vue, src/components/forms/CustomerInfo.vue, src/components/forms/DeliveryTime.vue, src/components/forms/PaymentMethod.vue, src/components/forms/ReviewOrder.vue
This partially addresses Issue #97 
In this PR, we change the stepper top bar to be a circular progress bar with no navigation components. We also change the bottom progress buttons to be nav buttons allowing the user to go back.
In future PRs we will complete treating #97 with animations and other loose ends.
=> feat: checkout progress nav refresh (partial)

src/components/forms/CheckoutNavBar.vue
Sometimes the CheckoutNavBar and the form portions of the component were touching, which we don't want.
=> chore: remove medium condition on y-margins for CheckoutNavBar component

src/App.vue, src/layouts/Store.vue
Moved `html, body` and `#app` styling to `App.vue` component as suggested in https://github.com/whynotearth/foodouken.com/pull/125#discussion_r411066753
=> refactor: moved root styling to App.vue

src/store/modules/store.js
Revert API calls on Store.vue to old endpoints.
> **WARNING**: This will break the store page.
=> refactor: revert to old API endpoint

.github/pull_request_template.md
This adds a template that will auto-populate the 'description' section every time someone creates a GitHub PR in the repo. Then, the PR opener can just fill it out. This will eliminate the need to copy and paste the template every time from some other source.
(Copy and pasted from BrowTricks PR for adding template: Adding such a template should help PR descriptions be more focused and thorough which should help produce faster and more effective reviews which should help the codebase be more navigable, extendable, rack up less tech debt, etc., etc.)
Some small changes from the template originally from BrowTricks:
* the 'type of pr' section is no longer a 'task list' in the GitHub markdown format, as GitHub treats those as literal task lists and displays them in the repo's PR list like so, …
=> Meta: Add PR template

src/assets/check.svg, src/components/inputs/CheckBox.vue
This PR has no related issue. I created a checkbox component to use everywhere at the system. 
You can see sample of checkbox here.
https://github.com/whynotearth/foodouken.com/issues/189#checkbox
*For New Features:* What feature are we adding? Explain your technical approach to doing this.
- Checkbox.vue is created to use a general checkbox in the system to provide consistency whole around the app. If you bind array to checkbox you have to provide value as well, then it push or pop the value accordingly. If you don't provide array it will give true or false.
As you see there are two attributes on input element which are `v-bind="$attrs"` and `v-on="$listeners"` . This makes binding events and attributes where this component is used. So we don't have to each event to emit at the …
=> checkbox component created

src/components/BaseAppBarHeader.vue, src/components/menu/MenuItem.vue, src/router/authRoutes.js, src/router/index.js, src/router/tenantCMSRoutes.js, src/store/modules/tenant.js, src/views/Menu.vue, src/views/MenuCategoryList.vue, src/views/SettingsAccount.vue
#258, tenantSlug safety checks and other bugs.
[x] Bug Fix
[x] Refactor
- Bug in categoryList view, data related to old categories not cleared on component destroyed.
- Made "3 dot menu" optional in MenuItem
- Fixed layout of Settings.vue
- Fixed text styles of Settings.vue
- Menu.vue has been made more minimal.
- tenantLayout.vue has been made a master layout with BaseAppBarHeader
- removed redundant BaseAppBarHeader from Settings.vue
- …
=> Feat/My Account, tenantLayout, safety checks for tenants, route to Account on login.

src/components/forms/CustomerInfo.vue, src/components/inputs/MaterialInput.vue
None.
Desktop still functions the same way for phone number input, but now its easier to enter on mobile.
Steps to reproduce bad UX on current site:
1. Go to start an order on https://foodouken.com/ with a mobile device
2. Notice in phone number field you can input text
3. ![IMG_7914](https://user-images.githubusercontent.com/44442621/87003257-4b866280-c189-11ea-8f3c-c8154348b255.png)
THE FIX:
1. Go to start an order on https://deploy-preview-316--foodouken.netlify.app/ with a mobile device
2. Notice in phone number field you have big number buttons on the software keyboard
3. ![IMG_7917](https://user-images.githubusercontent.com/44442621/87003341-707ad580-c189-11ea-973e-466 …
=> Big number input on phone software keyboards

src/router/index.js
Added scrollToTop on new page
No issue on record. When you are scrolled down the page and click a tenant you're viewport is at the same scroll distance from the top. A better experience would be to automatically scroll to top of page on a new router view.
Improve UX by having the app scroll to top when a user excepts it to and retain the last place they were viewing when going to a previous page.
Currently this happens:
1. Go to https://foodouken.com/
2. Scroll down to tenants and click any tenant. Notice page scrolls to top
3. Click back via Web Browser button or swipe left on mobile
4. Scroll down to tenants again and click any tenant
5. Notice the page does not scroll to top automatically the second time.
This …
=> Added savedPosition when going back a page

src/components/BaseSiteBanner.vue, src/utils/cookie.js
None
Give user the ability to dismiss the beta banner if they want
1. Go to https://deploy-preview-319--foodouken.netlify.app/
2. Notice the banner has an 'x' on top right. Click it.
3. Notice banner is gone and does not show on any subsequent views
The banner will come back after 7 days. This duration can be extended, but I think 7 days is good to start with.
=> Created a small cookie utility and added X svg button to dismiss banner

src/main.js, src/store/modules/home.js
No issue
Updating dataLayer for Google Enhanced eCommerce to know what position the tenants are loading at.
1. Download https://chrome.google.com/webstore/detail/dataslayer/ikbablmmjldhamhcldjjigniffkkjgpo?hl=en-US
2. Open the extension and make sure you are in 'json' view
3. Go to https://deploy-preview-307--foodouken.netlify.app/ and open DataSlayer to test it
https://i.imgur.com/aNz2sfH.png
This is just a start. It will be used properly in the future, with Meredith Core
=> Added impression datalayer to use with Google Enhanced eCommerce

src/views/Shop.vue
Fix for empty shop page:
> when I visit here, I don't see anything https://staging.foodouken.com/shop/paul-chris-luke-47
> 
> I get a 401 on https://stagingapi.whynot.earth/api/v0/authentication/ping
> is that related to what you fixed for browtricks?
There was a defective `isActive` checking in shop page on beforeRouteEnter. Disabled that rule.
=> hotfix: empty shop page

package.json, src/components/DuplicateAccount.vue, src/components/forms/CustomerInfo.vue, src/components/inputs/DuplicateAccount.vue, yarn.lock
#268 
[ ] Bug Fix
[ ] Refactor
Error was shown when someone tried to order who already had an account. This notifies a user that they already have an account and gives them the option to go to login page.
1. Go to https://deploy-preview-322--foodouken.netlify.app/shop/foodie-27/your-address
2. Select an item and start the order. Fill in any name
3. For email use an existing account **bamboo.chow@gmail.com**
4. Fill in any phone number
5. Notice that you get a popup that lets you go to login page
I think having a popup is better than just automatically redirecting them
=> Added popup modal with transition for redirect when account exists

src/components/cards/ProductCard.vue, src/components/cart/CartItem.vue
none.
[ ] Bug Fix
[ ] Refactor
All prices are now forced to always have 2 decimal places to stay consistent.
Before:
After:
Live Preview: https://deploy-preview-382--foodouken.netlify.app/
No longer will you see **$2.5** and **$3**. Now you will always see **$2.50**, **$3.00** etc...
=> Made price always have two decimal places to stay consistent 

src/views/Home.vue
none
[ ] Bug Fix
[ ] Refactor
The logo was square on HP, but now its rounded.
Before:
After:
Live Preview: https://deploy-preview-381--foodouken.netlify.app/
The reason this image is not a PNG is because for SEO reasons, so kept it a JPG. Just rounded it with css
=> made logo rounded, but SEO image is still square

src/main.js
#354 
[ ] Bug Fix
[ ] Refactor
Added dynamic function based on build setting. Anytime the build IS NOT 'production' then the environment for Rollbar will be staging. When in production the environment will be 'production'.
=> added conditions for Staging / Production builds for Rollbar
